### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by jeffreyroberts**
Fixes Issue #27 

I would imagine we can remove the other ExtensionRegistry at this time, but we can't, for some reason, somewhere else its loading it, but its working now

### CODE REVIEW

**Comment by jeffreyroberts** [comment]
Hope this works for yall

**Comment by jeffreyroberts** [comment]
grrr, I forgot something, and its a bit of a hack, but i might as well submit it and maybe someone can throw a quick change at it...

How can I add more commits to this pull request?

**Comment by rogerpro** [comment]
> How can I add more commits to this pull request?

just do `git push` again

**Comment by rogerpro** [comment]
CakeDC/cakephp-api requires `"cakedc/users": "^5.0"` whilst your CakePHPKitchen/CakeDC-API-Issue-27 requires `"cakedc/users": "^4.0"`

Also, please resend the PR to the new `develop` branch.

**Comment by jeffreyroberts** [comment]
will do, develop branch

**Comment by rogerpro** [comment]
Please also review [Coding Standards](https://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html). Thanks.

**Pull request closed without merging**
